### ISSUE TITLE
Disable text selection 

### ISSUE THREAD

**Issue by tusharmath** [Gisto/Gisto#58]
It feels like a web application because a user can select text in the app, and the cursor also changes. You can disable it with the following css - 

``` css
body{
  -webkit-user-select: none;
  cursor: default;
}
```
